### ISSUE TITLE
Month and Year forward/backward conflict inside reactive form

### ISSUE THREAD

**Issue by gamboaweb** [write2sv/ionic-date-picker#1] opened 2019-02-26 11:47 UTC
Hi. First of all congrats. Nice calendar picker.
I found a bug when using the calendar inside a reactive form wich has a submit button.
So, what happens is if you click on the arrows to view the next or previous months or on year view to previous and next years...the form gets submited.
I found a solution for it adding type='button' in line 12 for the respective 4 button in:
-> ionic-calendar-date-picker -> dist -> components -> date-picker-component.js
Just to let you know.

**Comment by write2sv** [comment] 2019-02-26 21:21
Hi @gamboaweb,

Thanks for your feedback. Will you be able to get me a sample repository that demonstrates this issue. Many thanks!

**Comment by gamboaweb** [comment] 2019-02-27 13:13
Hi @write2sv ... here it goes:
[https://github.com/gamboaweb/bugbuttonexample.git]
Just create an ionic 3 tabs template and install your calendar picker component and then replace the src folder from the link above.

**Comment by write2sv** [comment] 2019-02-28 19:40
Thanks for doing this @gamboaweb!

The issue is now fixed in 0.1.2

**Closed as completed by write2sv** 2019-02-28 19:40 UTC
